### ISSUE TITLE
问题：内存占用是per-connection还是其他

### ISSUE THREAD

**Issue by fantasticfears** [jaiminpan/pg_jieba#11]
你好，
我发现 pg_jieba 因为字典缘故，能占到 120MB 的内存，不知道作为插件，是按照每个连接打开呢，还是按照其他的参数？

**Comment by jaiminpan** [comment]
字段是共用，加载到内存中不共用，postgres是多进程， 而且session是可以有各自的分词配置

2017-08-10 15:26 GMT+08:00 Erick Guan <notifications@github.com>:

**Comment by fantasticfears** [comment]
postmaster 鉴权，然后对一个连接开一个 postgres 进程，这个内存代价好高。40 个连接就多付出了 40*100 了...

谢谢解答。
