### ISSUE TITLE
CentOS 7.4 和 PostgreSQL 10.0 下编译错误

### ISSUE THREAD

**Issue by gzliudan** [jaiminpan/pg_jieba#16]
export PATH=/usr/pgsql-10/bin:$PATH
cd pg_jieba
mkdir build
cd build
cmake ..

-- Setting pg_jieba build type -
CMake Warning at /usr/share/cmake/Modules/FindPostgreSQL.cmake:109 (message):
  Couldn't determine PostgreSQL configuration.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPostgreSQL.cmake:145 (fail_if)
  CMakeLists.txt:11 (find_package)

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY_DIRS
  PostgreSQL_INCLUDE_DIRS PostgreSQL_LIBRARIES) (found version "10.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindPostgreSQL.cmake:173 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/pg_jieba/build/CMakeFiles/CMakeOutput.log".

**Comment by liuliangbin** [comment]
请用最新的tag 版本， 按tag 版本README 描述安装。

**Comment by gzliudan** [comment]
切换到v1.0.1后，根据文档 https://github.com/jaiminpan/pg_jieba/tree/v1.0.1 的ReadMe，终于弄好了。请问自定义词典的格式？
