### ISSUE TITLE
jieba分词有没有更改搜索模式的函数

### ISSUE THREAD

**Issue by qianfangyuan** [jaiminpan/pg_jieba#19]
有没有办法可以在：搜索引擎模式、精确模式、全模式切换？

**Comment by gzliudan** [comment]
同问

**Comment by gzliudan** [comment]
看到配置里有 jiebacfg 和 jiebaqry

**Comment by jaiminpan** [comment]
HI,
这块目前没有并没有实现，欢迎提供相关patch。

**Comment by huzhengyao** [comment]
有些鸡肋， jiebacfg 和 jiebaqry 完全不够用，跟ElasticSearch还是比不了。 谁改改提供多几种配置，支持分到一个一个单独的字

**Comment by gzliudan** [comment]
应该可以自己定义的，只是没有文档

**Comment by jaiminpan** [comment]
New version support some choice. Close
