### ISSUE TITLE
能否支持多个自定义词典、切换分词模式？

### ISSUE THREAD

**Issue by gzliudan** [jaiminpan/pg_jieba#20]
能否支持多个自定义词典、切换分词模式？

**Comment by gzliudan** [comment]
看到配置里有 jiebacfg 和 jiebaqry ， 最好能多提供几种配置
多个自定义词典，不知道怎样设置

**Comment by jaiminpan** [comment]
自定义词典已经支持，请看reamde设置，切换分词模式暂时未支持。

**Comment by gzliudan** [comment]
但现在只支持一个自定义词典：jieba.user.dict.utf8，如果想同时使用几个自定义词典呢？

**Comment by jaiminpan** [comment]
暂不支持。

**Comment by jaiminpan** [comment]
Multi dict is supported. dict rename to `jieba_user.dict`. More detail in README
