### ISSUE TITLE
postgre新手求问怎么使用pg_jieba

### ISSUE THREAD

**Issue by changdy** [jaiminpan/pg_jieba#21]
使用rel_v1.0.1分支,安装成功
执行`select * from to_tsvector('jiebacfg', '小明硕士毕业于中国科学院计算所，后在日本京都大学深造')`;能够正确返回.
现在我想再这个数据库新建一张表,并且某字段使用结巴分词来进行优化.那么该字段需要进行一些额外的声明或者设置吗.

**Comment by jaiminpan** [comment]
请先学习PG，参考 https://yq.aliyun.com/articles/59251
