### ISSUE TITLE
cppjieba/Jieba.hpp: No such file or directory

### ISSUE THREAD

**Issue by Mrseven** [jaiminpan/pg_jieba#27]
[postgres@postgres build]$ make
Scanning dependencies of target pg_jieba
[100%] Building CXX object CMakeFiles/pg_jieba.dir/pg_jieba.cpp.o
/home/postgres/soft/postgresql-9.6.6/contrib/pg_jieba/pg_jieba.cpp:31:30: error: cppjieba/Jieba.hpp: No such file or directory
/home/postgres/soft/postgresql-9.6.6/contrib/pg_jieba/pg_jieba.cpp:35: error: ‘cppjieba’ is not a namespace-name
/home/postgres/soft/postgresql-9.6.6/contrib/pg_jieba/pg_jieba.cpp:35: error: expected namespace-name before ‘;’ token
/home/postgres/soft/postgresql-9.6.6/contrib/pg_jieba/pg_jieba.cpp:213: error: ‘Word’ was not declared in this scope
/home/postgres/soft/postgresql-9.6.6/contrib/pg_jieba/pg_jieba.cpp:213: error: template argument 1 is invalid
/home/postgres/soft/postgresql-9.6.6/contrib/pg_jieba/pg_jieba.cpp:213: error: template argument 2 is invalid

[postgres@localhost build]$ make 
[100%] Building CXX object CMakeFiles/pg_jieba.dir/pg_jieba.cpp.o
/home/postgres/soft/postgresql-10.3/contrib/pg_jieba/pg_jieba.cpp:31:30: fatal error: cppjieba/Jieba.hpp: No such file or directory
 #include "cppjieba/Jieba.hpp"
                              ^
compilation terminated.
make[2]: *** [CMakeFiles/pg_jieba.dir/pg_jieba.cpp.o] Error 1
make[1]: *** [CMakeFiles/pg_jieba.dir/all] Error 2
make: *** [all] Error 2

**Comment by jaiminpan** [comment]
Do you follow the guide?
```
Init submodule
cd pg_jieba

# initilized sub-project
git submodule update --init --recursive
```
