### ISSUE TITLE
64位ubuntu18下postgres10不能创建pg_jieba

### ISSUE THREAD

**Issue by webbery** [jaiminpan/pg_jieba#33]
在ubuntu下编译完成了，make install也没有问题
但是在postgres中测试的时候出现如下错误信息：
~~~
colern=# create extension pg_jieba;
FATAL:  cannot create PGC_POSTMASTER variables after startup
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
~~~
请问该如何解决？

**Comment by jaiminpan** [comment]
Thanks for reporting. 
Fix at commit 3264b708e1c5f4a1f36d985196c89fadb11cf223.

There are two workround. 
1.  Set postgresql.conf `shared_preload_libraries = 'pg_jieba.so'`
2. Use the latest master. Then install again.
