### ISSUE TITLE
为什么‘CEO，走上人生巅峰。’这部份不会被分词？

### ISSUE THREAD

**Issue by smoothdvd** [jaiminpan/pg_jieba#35]
看[http://cppjieba-webdemo.herokuapp.com/](http://cppjieba-webdemo.herokuapp.com/)页面里是可以对英文进行分词的。

**Comment by jaiminpan** [comment]
Fixed at fc11a917e4f50a8abb5da6ebf56c1fbd427b9a8f. Please update to latest master then retry
