### ISSUE TITLE
pg 10.10 不支持

### ISSUE THREAD

**Issue by zbkjbi** [jaiminpan/pg_jieba#43]
翻了一下日志报的是Segmentation fault；之前我有关注这个issue https://github.com/jaiminpan/pg_jieba/issues/42 ;
错误的提示差不多。
pg11我尝试了已经ok了。。但是pg10还是会报错。
请问下还有什么解决方法吗

**Comment by zbkjbi** [comment]
服务器日志如下：

2019-10-11 14:05:17.907 HKT [17889] LOG:  server process (PID 7572) was terminated by signal 11: Segmentation fault
2019-10-11 14:05:17.907 HKT [17889] DETAIL:  Failed process was running: create extension pg_jieba;
2019-10-11 14:05:17.907 HKT [17889] LOG:  terminating any other active server processes
2019-10-11 14:05:17.908 HKT [6217] WARNING:  terminating connection because of crash of another server process

编译的时候也没有报错

[root@zib-bi-postgresql-001 build]# cmake .. -DCMAKE_CXX_FLAGS="-Wall -std=c++11" -DCMAKE_PREFIX_PATH=/usr/pgsql-10
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Setting pg_jieba build type -
-- Found PostgreSQL: /usr/pgsql-10/lib (found version "10.10")
-- PostgreSQL include dirs: /usr/pgsql-10/include;/usr/pgsql-10/include/server
-- PostgreSQL library dirs: /usr/pgsql-10/lib
-- PostgreSQL libraries:    pq
-- POSTGRESQL_EXECUTABLE is /usr/pgsql-10/bin/postgres
-- Configuring done
-- Generating done
-- Build files have been written to: /var/lib/pgsql/pg_jieba/build
[root@zib-bi-postgresql-001 build]# make install
Scanning dependencies of target pg_jieba
[ 50%] Building C object CMakeFiles/pg_jieba.dir/pg_jieba.c.o
/var/lib/pgsql/pg_jieba/pg_jieba.c:247:1: warning: ‘DefineCustomConfigVariables’ was used with no prototype before its definition [-Wmissing-prototypes]
 DefineCustomConfigVariables()
 ^
[100%] Building CXX object CMakeFiles/pg_jieba.dir/jieba.cpp.o
Linking CXX shared library pg_jieba.so
[100%] Built target pg_jieba
Install the project...
-- Install configuration: ""
-- Installing: /usr/pgsql-10/lib/pg_jieba.so
-- Up-to-date: /usr/pgsql-10/share/extension/pg_jieba.control
-- Up-to-date: /usr/pgsql-10/share/extension/pg_jieba--1.1.1.sql
-- Up-to-date: /usr/pgsql-10/share/tsearch_data/jieba_base.dict
-- Up-to-date: /usr/pgsql-10/share/tsearch_data/jieba_hmm.model
-- Up-to-date: /usr/pgsql-10/share/tsearch_data/jieba_user.dict
-- Up-to-date: /usr/pgsql-10/share/tsearch_data/jieba.stop
-- Up-to-date: /usr/pgsql-10/share/tsearch_data/jieba.idf

确认是check了最新的版本下来

**Comment by jaiminpan** [comment]
我无法确认那么多版本。手头正好有一个10.4的版本。顺手测试了。并没有发现问题。。
所以，等有空了，我升级了pg 才能验证是否有问题。。

![Screen Shot 2019-10-11 at 7 00 09 PM](https://user-images.githubusercontent.com/1400297/66646650-61e2aa80-ec59-11e9-8b87-574eb6b5137f.png)

**Comment by jaiminpan** [comment]
找到台10.10的机器并进行测试。能正常工作。
如果你有新的信息可以提供，再看是否需要修复

![Screen Shot 2019-10-12 at 12 18 10 PM](https://user-images.githubusercontent.com/1400297/66694818-66a36f00-ecea-11e9-87ee-f7df0618e338.png)

**Comment by jaiminpan** [comment]
我怀疑你之前尝试安装的pg_jieba 并没有在你的10.10上清理干净。你可以尝试用一个新的pg10.10进行测试。

**Comment by zbkjbi** [comment]
感谢关注。我先试试用一个新的pg10.10进行安装

**Comment by zbkjbi** [comment]
感谢关注。我先试试用一个新的pg10.10进行安装

**Comment by zbkjbi** [comment]
我准备了一台新的pg10.10进行安装已经安装成功了。
但是在旧的pg10.10还是无法安装成功。
请问下。除了把pg_jieba make install 后的文件删除掉。把build 里边的文件清空。还需要清理哪一些文件才能够清理干净

**Comment by jaiminpan** [comment]
如果是在postgresql.conf 配置文件里配置的。那需要安装后重启。重启数据库 应该会解决你的问题
