### ISSUE TITLE
make 出错

### ISSUE THREAD

**Issue by gansaihua** [jaiminpan/pg_jieba#44]
# make 
[ 50%] Building C object CMakeFiles/pg_jieba.dir/pg_jieba.c.o
/usr/local/pg_jieba/pg_jieba.c:19:27: fatal error: utils/varlena.h: No such file or directory
 #include "utils/varlena.h"
                           ^
compilation terminated.
make[2]: *** [CMakeFiles/pg_jieba.dir/pg_jieba.c.o] Error 1
make[1]: *** [CMakeFiles/pg_jieba.dir/all] Error 2
make: *** [all] Error 2

**Comment by jaiminpan** [comment]
Please see following issue if helped.  
https://github.com/jaiminpan/pg_jieba/issues/15

OR Reference `Compile Failed Q&A` in  README.md
