### ISSUE TITLE
FTS Configurations 顯示問題.

### ISSUE THREAD

**Issue by kronaking** [jaiminpan/pg_jieba#5]
預設 FTS Configurations 顯示為:
>CREATE TEXT SEARCH CONFIGURATION jiebacfg (
>  PARSER = jieba
>);
>ALTER TEXT SEARCH CONFIGURATION jiebacfg ADD MAPPING FOR a WITH simple;
>ALTER TEXT SEARCH CONFIGURATION jiebacfg ADD MAPPING FOR d WITH simple;
>ALTER TEXT SEARCH CONFIGURATION jiebacfg ADD MAPPING FOR n WITH simple;
>COMMENT ON TEXT SEARCH CONFIGURATION jiebacfg IS 'configuration for jieba';

=> v 沒有呈現出來

執行:
> ALTER TEXT SEARCH CONFIGURATION jiebacfg ADD MAPPING FOR v WITH simple;

結果:
>ERROR:  duplicate key value violates unique constraint "pg_ts_config_map_index"
>DETAIL:  Key (mapcfg, maptokentype, mapseqno)=(377086, 3, 1) already exists.

=> v 確實有存在

環境:
PostgreSQL: 9.4.5

**Comment by kronaking** [comment]
後來用 psql 直接查證是正常的, 應該是 pgAdmin3 的問題,

 # \dF+ jiebacfg
>Text search configuration "public.jiebacfg"
>Parser: "public.jieba"
> Token | Dictionaries
>-------+--------------
> a     | simple
> d     | simple
> n     | simple
> v     | simple

**Comment by jaiminpan** [comment]
好的，感谢找到原因。
