### ISSUE TITLE
postgres14 分词和预期结果不一致

### ISSUE THREAD

**Issue by zhuqingchao** [jaiminpan/pg_jieba#54]
首页文档中示例
`select * from to_tsquery('jiebacfg', '是拖拉机学院手扶拖拉机专业的。不用多久，我就会升职加薪，当上CEO，走上人生巅峰。');`
应该返回
`'拖拉机' & '学院' & '手扶拖拉机' & '专业' & '不用' & '多久' & '会' & '升职' & '加薪' & '当上' & 'ceo' & '走上' & '人生' & '巅峰'`
实际返回
`'拖拉机' <-> '学院' <-> '手扶拖拉机' <-> '专业' <3> '不用' <-> '多久' <4> '会' <-> '升职' <-> '加薪' <2> '当上' <-> 'ceo' <2> '走上' <-> '人生' <-> '巅峰'`

**Comment by zhuqingchao** [comment]
@liuxintang c++ 版本不对？

**Comment by liuxintang** [comment]
@zhuqingchao C++11吧应该是。
您的PG14编译过程的命令和pg_jieba编译的命令可以发一下我试试嘛。

**Comment by zhuqingchao** [comment]
> @zhuqingchao C++11吧应该是。 您的PG14编译过程的命令和pg_jieba编译的命令可以发一下我试试嘛。
有些久了，网上通用教程就行。

**Comment by liuxintang** [comment]
我先自己再试试，有问题再咨询。不过还是要谢谢。
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月30日 15:31 |
| 收件人 | ***@***.***> |
| 抄送人 | Liu ***@***.***> ,
***@***.***> |
| 主题 | Re: [jaiminpan/pg_jieba] postgres14 分词和预期结果不一致 (Issue #54) |

@zhuqingchao C++11吧应该是。 您的PG14编译过程的命令和pg_jieba编译的命令可以发一下我试试嘛。
有些久了，网上通用教程就行。
