### ISSUE TITLE
怎么支持postgresql版本15呢

### ISSUE THREAD

**Issue by lanyuer** [jaiminpan/pg_jieba#57]
ERROR:  Server is version 15, library is version 13.incompatible library "/usr/lib/postgresql/15/lib/pg_jieba.so": version mismatch 

ERROR:  incompatible library "/usr/lib/postgresql/15/lib/pg_jieba.so": version mismatch
SQL 状态: XX000
详细： Server is version 15, library is version 13.

**Comment by lanyuer** [comment]
解决了：
Q: Ubuntu, To specify version of pg(missing: PostgreSQL_TYPE_INCLUDE_DIR)
A: cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/10/server ..

**Comment by ilwyiworld** [comment]
> 解决了： Q: Ubuntu, To specify version of pg(missing: PostgreSQL_TYPE_INCLUDE_DIR) A: cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/10/server ..

这个咋解决的呀，这个目录的地址应该填啥

**Comment by liangnet** [comment]
详细： Server is version 15, library is version 13.

這個錯誤發生在
RUN apk --no-cache add postgresql15-dev

如果你不指定版本, 會預設安裝最新版 postgresqlXX-dev
