### ISSUE TITLE
ubuntu 18 PG15 版本下无法编译

### ISSUE THREAD

**Issue by ilwyiworld** [jaiminpan/pg_jieba#58]
Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR)

**Comment by cmj2002** [comment]
我在 debian bookworm, PG15 下成功进行了编译，你所说的情况应该可以被 `apt-get install libpq-dev postgresql-server-dev-15` 解决。
