### ISSUE TITLE
斷詞解析問題

### ISSUE THREAD

**Issue by kronaking** [jaiminpan/pg_jieba#6]
使用預設 FTS Configurations 來調用斷詞解析：

> SELECT \* FROM ts_debug('jiebacfg', '我来到北京清华大学;他来到了网易杭研大厦;小明硕士毕业于中国科学院计算所，后在日本京都大学深造')

結果:

> alias | description |    token     | dictionaries | dictionary |    lexemes
> -------+-------------+--------------+--------------+------------+----------------
> n     | noun        | 我           | {simple}     | simple     | {我}
> n     | noun        | 来到         | {simple}     | simple     | {来到}
> n     | noun        | 北京         | {simple}     | simple     | {北京}
> n     | noun        | 清华大学     | {simple}     | simple     | {清华大学}
> n     | noun        | ;            | {simple}     | simple     | {;}
> n     | noun        | 他           | {simple}     | simple     | {他}
> n     | noun        | 来到         | {simple}     | simple     | {来到}
> n     | noun        | 了           | {simple}     | simple     | {了}
> n     | noun        | 网易         | {simple}     | simple     | {网易}
> n     | noun        | 杭研         | {simple}     | simple     | {杭研}
> n     | noun        | 大厦         | {simple}     | simple     | {大厦}
> n     | noun        | ;            | {simple}     | simple     | {;}
> n     | noun        | 小明         | {simple}     | simple     | {小明}
> n     | noun        | 硕士         | {simple}     | simple     | {硕士}
> n     | noun        | 毕业         | {simple}     | simple     | {毕业}
> n     | noun        | 于           | {simple}     | simple     | {于}
> n     | noun        | 中国科学院   | {simple}     | simple     | {中国科学院}
> n     | noun        | 计算所       | {simple}     | simple     | {计算所}
> n     | noun        | ，           | {simple}     | simple     | {，}
> n     | noun        | 后           | {simple}     | simple     | {后}
> n     | noun        | 在           | {simple}     | simple     | {在}
> n     | noun        | 日本京都大学 | {simple}     | simple     | {日本京都大学}
> n     | noun        | 深造         | {simple}     | simple     | {深造}
> (23 rows)

=> 詞性皆歸類成 n

**Comment by jaiminpan** [comment]
谢谢，不过因为之前cpp版的结巴分词还不支持词性的获取，所以当时pg_jieba开发的时候直接都用了n来代替。

**Comment by yanyiwu** [comment]
@jaiminpan  支持呀，这个Tag 函数不就是吗？   https://github.com/jaiminpan/pg_jieba/blob/master/libjieba/jieba/Jieba.hpp#L47

**Comment by jaiminpan** [comment]
@yanyiwu 好的。谢谢提醒。之后抽空修复

**Comment by jaiminpan** [comment]
v2.0.0 及以上版本已支持
