### ISSUE TITLE
server closed the connection unexpectedly when test on windows 64

### ISSUE THREAD

**Issue by connor2059** [jaiminpan/pg_jieba#8]
I compile it for windows with vs2015.
create extension successful but when i run 
select to_tsvector('jiebacfg', '小明是个好孩子');

it turns out to be:

server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

what may cause the problem?
what shold i do?

**Comment by jaiminpan** [comment]
Yes, the project is not tested on windows. It seems the crash happens.
Could you provide some backtrace of the crash?

2016-09-08 20:26 GMT+08:00 connor2059 <notifications@github.com>:

**Comment by connor2059** [comment]
Debug assertion faild!
...

Expression c>-1 && c<255
